### ISSUE TITLE
ステップ7: タスクを登録・更新・削除できるようにしよう

### ISSUE THREAD

**Issue by hiroyasu-shiratori** [hiroyasu-shiratori/Fablic-training#12]
## リンク
- issue
  - [x] [ステップ7-1: タスクの一覧画面の作成 · Issue #13](https://github.com/hiroyasu-shiratori/Fablic-training/issues/13)
  - [x] [ステップ7-2: タスクの作成画面の作成 · Issue #14](https://github.com/hiroyasu-shiratori/Fablic-training/issues/14)
  - [x] [ステップ7-3: タスクの詳細画面の作成 · Issue #15](https://github.com/hiroyasu-shiratori/Fablic-training/issues/15)
  - [x] [ステップ7-4: タスクの編集画面の作成 · Issue #16](https://github.com/hiroyasu-shiratori/Fablic-training/issues/16)
- 研修内容
  - [ステップ7: タスクを登録・更新・削除できるようにしよう](https://github.com/hiroyasu-shiratori/Fablic-training/tree/master/docs#%E3%82%B9%E3%83%86%E3%83%83%E3%83%977-%E3%82%BF%E3%82%B9%E3%82%AF%E3%82%92%E7%99%BB%E9%8C%B2%E6%9B%B4%E6%96%B0%E5%89%8A%E9%99%A4%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%82%88%E3%81%86)
- 参考リンク
  - [Action View の概要 - Railsガイド](https://railsguides.jp/action_view_overview.html)
  - [Action Controller の概要 - Railsガイド](https://railsguides.jp/action_controller_overview.html)
  - [Rails のルーティング - Railsガイド](https://railsguides.jp/routing.html)
  - [RailsにおけるMVC(モデル/ビュー/コントローラ) - Ruby on Rails入門](https://www.javadrive.jp/rails/ini/index7.html)
  - [【Rails】新規アプリの作成 - Qiita](https://qiita.com/Hal_mai/items/23c553e4af19bfc75c68)
  - [railsでページ作成をする - Qiita](https://qiita.com/you8/items/a7624fef49dedfdc71ae)
  - [こりゃ便利！RailsのModelやControllerを削除する方法 | Yuuの悠々自適Blog](https://yuu.1000quu.com/delete_the_model_and_controller_in_rails)
  - [【Rails】resourcesメソッドを使ってルーティングを定義しよ | Pikawaka - ピカ1わかりやすいプログラミング用語サイト](https://pikawaka.com/rails/resources)
  - [【Rails入門】スタイルシート（CSS）を使ってWebアプリを装飾しよう | 侍エンジニアブログ](https://www.sejuku.net/blog/64731)
  - [Railsの品質を上げるRuboCopとは？インストールや使い方を紹介！ | キツネの惑星](https://kitsune.blog/rails-rubocop)
  - [【Rails5】はじめてのプロジェクトでRubocopから指摘されたエラーのまとめ - Qiita](https://qiita.com/yokoyan/items/76e6b330a6b9d908d6fb)
  - [RuboCop is 何？ - Qiita](https://qiita.com/tomohiii/items/1a17018b5a48b8284a8b)

## 進捗
- [x] タスクの一覧画面、作成画面、詳細画面、編集画面を作成しましょう
  - [x] `rails generate` コマンドでコントローラとビューを作成します
  - [x] コントローラとビューに必要な実装を追加しましょう
  - [x] 作成、更新、削除後はそれぞれflashメッセージを画面に表示させましょう
- [x] `routes.rb` を編集して、 `http://localhost:3000/` でタスクの一覧画面が表示されるようにしましょう
- [x] GitHub上でPRを作成してレビューしてもらいましょう
  - [x] 今後、PRが大きくなりそうだったらPRを2回以上に分けることを検討しましょう

**Comment by hiroyasu-shiratori** [comment]
デサイン等は後にやるとしてまず必要最低限の機能を作っていきます

**Comment by hiroyasu-shiratori** [comment]
Action ViewとAction Controllerの概要をざっくり全部読みました

**Comment by hiroyasu-shiratori** [comment]
### コントローラーの作成
名前は複数形が良いらしいのでtasksにします
```
$ rails g controller tasks
Running via Spring preloader in process 74822
      create  app/controllers/tasks_controller.rb
      invoke  erb
      create    app/views/tasks
      invoke  test_unit
      create    test/controllers/tasks_controller_test.rb
      invoke  helper
      create    app/helpers/tasks_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/tasks.coffee
      invoke    scss
      create      app/assets/stylesheets/tasks.scss
```

**Comment by hiroyasu-shiratori** [comment]
viewまで一度に作成できるらしいので一度コントローラーを削除する

**Comment by hiroyasu-shiratori** [comment]
### コントローラーの削除
viewまで一度に作成できるらしいので一度コントローラーを削除
```
$ rails destroy controller tasks
Running via Spring preloader in process 75307
      remove  app/controllers/tasks_controller.rb
      invoke  erb
      remove    app/views/tasks
      invoke  test_unit
      remove    test/controllers/tasks_controller_test.rb
      invoke  helper
      remove    app/helpers/tasks_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      remove      app/assets/javascripts/tasks.coffee
      invoke    scss
      remove      app/assets/stylesheets/tasks.scss
```

**Comment by hiroyasu-shiratori** [comment]
### コントローラーとビューの作成
とりあえずindexで作成
```
$ rails g controller tasks index
Running via Spring preloader in process 75425
      create  app/controllers/tasks_controller.rb
       route  get 'tasks/index'
      invoke  erb
      create    app/views/tasks
      create    app/views/tasks/index.html.erb
      invoke  test_unit
      create    test/controllers/tasks_controller_test.rb
      invoke  helper
      create    app/helpers/tasks_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/tasks.coffee
      invoke    scss
      create      app/assets/stylesheets/tasks.scss
```

**Comment by hiroyasu-shiratori** [comment]
### ルーティングの確認
`config/routes.rb`に書いてある内容の通りか確認
```
$ rails routes
     Prefix Verb URI Pattern            Controller#Action
tasks_index GET  /tasks/index(.:format) tasks#index
```

**Comment by hiroyasu-shiratori** [comment]
### 動作確認
一度動かして動作確認
```
$ rails s
=> Booting Puma
=> Rails 5.0.7.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.6 (ruby 2.5.7-p206), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
```

`http://localhost:3000/tasks/index`にアクセス
```
Started GET "/tasks/index" for ::1 at 2021-05-07 11:41:58 +0900
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by TasksController#index as HTML
  Rendering tasks/index.html.erb within layouts/application
  Rendered tasks/index.html.erb within layouts/application (1.6ms)
Completed 200 OK in 163ms (Views: 156.0ms | ActiveRecord: 0.0ms)
```
![image](https://user-images.githubusercontent.com/82800686/117390600-6badbc00-af29-11eb-868d-1b8782ccffe6.png)

一度この時点でコミットをします

**Comment by hiroyasu-shiratori** [comment]
`/tasks`でindexを表示してほしいのでルーティングを変える必要がありそう
![image](https://user-images.githubusercontent.com/82800686/117390967-07d7c300-af2a-11eb-9d97-7be27aaa3b5f.png)

**Comment by hiroyasu-shiratori** [comment]
`resources`を使うと`index, show, new, create, edit, update, destroy`を個別に宣言しなくても使えるようになるらしい

**Comment by hiroyasu-shiratori** [comment]
`config/routes.rb`の中身を書き換える
```ruby
Rails.application.routes.draw do
  resources :tasks
end
```
ルーティングを確認
```
$ rails routes
   Prefix Verb   URI Pattern               Controller#Action
    tasks GET    /tasks(.:format)          tasks#index
          POST   /tasks(.:format)          tasks#create
 new_task GET    /tasks/new(.:format)      tasks#new
edit_task GET    /tasks/:id/edit(.:format) tasks#edit
     task GET    /tasks/:id(.:format)      tasks#show
          PATCH  /tasks/:id(.:format)      tasks#update
          PUT    /tasks/:id(.:format)      tasks#update
          DELETE /tasks/:id(.:format)      tasks#destroy
```
上手く言ってるのでコミット
![image](https://user-images.githubusercontent.com/82800686/117403009-74f75280-af42-11eb-9570-d4dc890741aa.png)

**Comment by hiroyasu-shiratori** [comment]
タスクの一覧画面、作成画面、詳細画面、編集画面は新たにブランチを切って1機能づつレビューを貰うことにします

**Comment by hiroyasu-shiratori** [comment]
テーブルのcssをhtmlファイル直書きではなく、`app/assets/stylesheets/application.css`に書くことにします
共通で変更したいcssはここに書くほうが良いらしい

**Comment by hiroyasu-shiratori** [comment]
途中までコミットした状態ですがブランチを分けます

**Comment by hiroyasu-shiratori** [comment]
RuboCopの導入をします

**Comment by hiroyasu-shiratori** [comment]
全ての機能を実装したのでマージ
